tasker/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from . import views

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('tasks', views.task_listings, name='task_listings'),
    path('calender', views.CalendarView.as_view(), name='calender_listings'),
    path('mytasks', views.own_task_listings, name='own_task_listings'),
    path('tasks_history', views.task_history, name='task_history'),
    path('rank', views.user_rank, name='user_rank'),
    path('announcements', views.announcements, name='announcements'),
    path('announcement_creation', views.announcement_creation,
         name='announcement_creation'),
    path('announcement/<int:pk>/', views.announcement, name='announcement'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('invite/', views.inviteView, name='invite'),
    path('create/', views.task_creation, name='task_creation'),
    path('member_list/', views.member_list, name='member_list'),
    path('task/<int:pk>/', views.task_detail, name='task_detail'),
    path('update/<int:pk>/', views.task_update, name='task_update'),
    path('delete/<int:pk>/', views.task_delete, name='task_delete'),
    path('task_done/<int:pk>/', views.task_done, name='task_done'),
    path('apply/<int:pk>/', views.task_apply, name='task_apply'),
    path('user/<int:pk>/', views.user_profile, name='user_profile'),
    path('edit/<int:pk>/', views.edit_profile, name='edit_profile'),
]

tasks/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


class Task(models.Model):

    assign_status_options = (
        (0, 'Unasigned'),
        (1, 'Assigned'),
    )

    status_options = (
        (0, 'On going'),
        (1, 'Done'),
    )

    task_name = models.CharField(max_length=100)
    assign_date = models.DateField(default=datetime.now, blank=True)
    last_date = models.DateField(default=datetime.now, blank=True)
    description = models.CharField(max_length=1000, blank=True)
    url = models.URLField(max_length=100, null=True)
    status = models.BooleanField(choices=status_options, null=True)
    assign_status = models.BooleanField(
        choices=assign_status_options, null=True, default=0)
    code = models.CharField(max_length=8, unique=True, null=True)
    member = models.ForeignKey(
        'User', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.task_name


class User(AbstractUser):

    designation_options = (
        ('General Member', 'General Member'),
        ('Executive', 'Executive'),
        ('Senior Executive', 'Senior Executive'),
        ('Assistant Director', 'Assistant Director'),
        ('Director', 'Director'),
    )

    department_options = (
        ('HR', 'Human Resources'),
    )

    status_options = (
        (0, 'Free'),
        (1, 'Busy'),
    )

    in_club_name = models.CharField(max_length=70, blank=True)
    department = models.CharField(
        max_length=50, choices=department_options, blank=True)
    designation = models.CharField(
        max_length=20, choices=designation_options, blank=True)
    display_picture = models.ImageField(blank=True, null=True)
    status = models.BooleanField(
        choices=status_options, default=1, null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    hr_points = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.in_club_name


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateField(default=datetime.now, blank=True)
    end_time = models.DateField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title


class Announcements(models.Model):

    tag = (
        (0, 'None'),
        (1, 'Everyone'),
    )

    title = models.CharField(max_length=200)
    picture = models.ImageField(blank=True, null=True)
    about = models.TextField(blank=True, null=True, max_length=1000)
    instructions = models.TextField(blank=True, null=True, max_length=1000)
    url = models.URLField(blank=True, null=True)
    tagged = models.BooleanField(choices=tag, default=0, null=True, blank=True)
    event_date = models.DateField(default=datetime.now, blank=True)
    duration = models.CharField(max_length=100, blank=True, null=True)
    platform = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms import fields, models

from .models import Task, User, Announcements

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'in_club_name',
            'first_name',
            'last_name',
            'email',
            'department',
            'designation',
            'display_picture'
        )
        field_classes = {'username': UsernameField}


class TaskModelForm(forms.ModelForm):

    last_date = forms.DateField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Task

        fields = (
            'task_name',
            'last_date',
            'description',
            'url',
            'status',
            'assign_status',
            'code',
            'member',
        )


class AnnouncementsModelForm(forms.ModelForm):

    event_date = forms.DateField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Announcements

        fields = (
            'title',
            'picture',
            'about',
            'instructions',
            'url',
            'tagged',
            'event_date',
            'duration',
            'platform',
        )


class TaskApplyModelForm(forms.ModelForm):

    class Meta:
        model = Task

        fields = (
            'status',
            'assign_status',
            'member',
        )


class TaskForm(forms.Form):
    task_name = forms.CharField()
    last_date = forms.DateField(input_formats=['%d/%m/%Y'])
    description = forms.CharField(max_length=200)
    url = forms.URLField()

templates/_alerts.html
{% if messages %} {% for message in messages %}
<div id="message" class="container">
  <div
    class="alert alert-{{ message.tags }} alert-dismissible text-center"
    role="alert"
  >
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>
      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error: {% else %}
      {{ message.tags|title }} {% endif %}
    </strong>
    {{ message }}
  </div>
</div>
{% endfor %} {% endif %}

templates/announcement_creation.html
{% extends 'base.html' %} {% block title %} | Invite {% endblock %} {% block content %}


<!-- <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">create</button>
</form> -->


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex h-screen bg-gray-200 items-center justify-center  mt-40 mb-40">
        <div class="grid bg-white rounded-lg shadow-xl w-11/12 md:w-9/12 lg:w-1/2">
            <div class="flex justify-center py-4">
                <div class="flex bg-purple-200 rounded-full md:p-4 p-2 border-2 border-purple-300">
                    <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
                </div>
            </div>

            <div class="flex justify-center">
                <div class="flex">
                    <h1 class="text-gray-600 font-bold md:text-2xl text-xl">Add Announcements</h1>
                </div>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_username">Title</label>
                <input type="text" name="title" maxlength="200" required="" id="id_title" class=" py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent " />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7 ">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold " for="id_in_club_name ">About</label>
                <input name="about" maxlength="1000" id="id_about" class="py-8 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7 ">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold " for="id_in_club_name ">Instructions</label>
                <input name="instructions" maxlength="1000" id="id_instructions" class="py-16 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_username">URL</label>
                <input type="url" name="url" maxlength="200" id="id_url" class=" py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent " />
            </div>


            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7 ">
                <div class="grid grid-cols-1 ">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold " for="id_event_date">Event Date</label>
                    <input type="text" name="event_date" required="" id="id_event_date" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent " type="text
                    " placeholder="Input 2 " />
                </div>



                <div class="grid grid-cols-1 ">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold " for="id_duration">Duration</label>
                    <input type="text" name="duration" maxlength="100" id="id_duration" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent " type="text
                    " placeholder="Input 2 " />
                </div>
            </div>


            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7 ">
                <div class="grid grid-cols-1 ">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold " for="id_tagged">Tag People</label>
                    <select name="tagged" id="id_tagged" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent ">
                        <option value="0">None</option>
                      
                        <option value="1">Everyone</option>
                      
                      </select>
                </div>

                <div class="grid grid-cols-1 ">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold " for="id_platform">Platform</label>
                    <input type="text" name="platform" maxlength="100" id="id_platform" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent " type="text
                    " placeholder="Input 2 " />
                </div>
            </div>


            <div class="grid grid-cols-1 mt-5 mx-7 ">
                <label for="id_picture" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold mb-1 ">Upload Photo</label>
                <div class='flex items-center justify-center w-full'>
                    <label class='flex flex-col border-4 border-dashed w-full h-32 hover:bg-gray-100 hover:border-purple-300 group'>
                        <div class='flex flex-col items-center justify-center pt-7'>
                        <svg class="w-10 h-10 text-purple-400 group-hover:text-purple-600 " fill="none " stroke="currentColor " viewBox="0 0 24 24 " xmlns="http://www.w3.org/2000/svg "><path stroke-linecap="round " stroke-linejoin="round
                        " stroke-width="2 " d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z "></path></svg>
                        <p class='lowercase text-sm text-gray-400 group-hover:text-purple-600 pt-1 tracking-wider'>Select a photo</p>
                        </div>
                        <input type="file" name="picture" accept="image/*" id="id_picture"/>
                </label>
                </div>
            </div>

            <div class='flex items-center justify-center  md:gap-8 gap-4 pt-5 pb-5'>
                <button class='w-auto bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'><a href="{% url "announcements" %} ">Cancel</a></button>
                <button type="submit " class='w-auto bg-purple-500 hover:bg-purple-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'>Create</button>
            </div>

        </div>
    </div>
</form>


{% endblock content %}

templates/task_creation.html
{% extends 'base.html' %}


{% block title %} | Create {% endblock %}


{% block content %}


<form method="post">
    {% csrf_token %}
    <div class="flex h-screen bg-gray-200 items-center justify-center  mt-10 mb-10">
        <div class="grid bg-white rounded-lg shadow-xl w-11/12 md:w-9/12 lg:w-1/2">
            <div class="flex justify-center py-4">
            <div class="flex bg-purple-200 rounded-full md:p-4 p-2 border-2 border-purple-300">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-earmark-plus-fill" viewBox="0 0 16 16">
                    <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM8.5 7v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 1 0z"/>
                </svg>
            </div>
            </div>

            <div class="flex justify-center">
            <div class="flex">
                <h1 class="text-gray-600 font-bold md:text-2xl text-xl upper">Add Task</h1>
            </div>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_task_name">Task Name</label>
                <input type="text" name="task_name" maxlength="100" required="" id="id_task_name" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Task Name" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_last_date" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Last Date</label>
                <input type="text" name="last_date" required="" id="id_last_date" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Pick a Date" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_description" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_task_name">Description</label>
                <input type="text" name="description" maxlength="1000" id="id_description" class="py-8 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Add Description" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_url" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Neccesary Url</label>
                <input type="url" name="url" maxlength="100" required="" id="id_url" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Url" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_member" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Assign a member</label>
                <select name="member" id="id_member" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent">
                    
                    {% for user in users %}
                        <option value={{ user.id }}>{{ user.in_club_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_code" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Task Code</label>
                <input type="text" name="code" maxlength="8" id="id_code" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Input 3" value="{{ code }}"/>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7">
                <div class="grid grid-cols-1">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Status</label>
                    <select name="status" required="" id="id_status" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent">
                        <option value="0">On Going</option>
                        <option value="1">Done</option>
                    </select>
                </div>

                <div class="grid grid-cols-1">
                    <label for="id_assign_status" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Assingment Status</label>
                    <select name="assign_status" required="" id="id_assign_status" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent">
                        <option value="0">Unassigned</option>

                        <option value="1">Assigned</option>

                    </select>
                </div>
            </div>

            <div class='flex items-center justify-center  md:gap-8 gap-4 pt-5 pb-5'>
                <button class='w-auto bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'><a href="{% url "task_listings" %}">Cancel</a></button>
                <button type="submit" class='w-auto bg-purple-500 hover:bg-purple-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'>Create</button>
            </div>

        </div>
    </div>
</form>
{% endblock content %}

templates/task_update.html
{% extends 'base.html' %}


{% block title %} | Update {% endblock %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="flex h-screen bg-gray-200 items-center justify-center  mt-32 mb-32">
        <div class="grid bg-white rounded-lg shadow-xl w-11/12 md:w-9/12 lg:w-1/2">
            <div class="flex justify-center py-4">
            <div class="flex bg-purple-200 rounded-full md:p-4 p-2 border-2 border-purple-300">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-layer-forward" viewBox="0 0 16 16">
                    <path d="M8.354.146a.5.5 0 0 0-.708 0l-3 3a.5.5 0 0 0 0 .708l1 1a.5.5 0 0 0 .708 0L7 4.207V12H1a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1H9V4.207l.646.647a.5.5 0 0 0 .708 0l1-1a.5.5 0 0 0 0-.708l-3-3z"/>
                    <path d="M1 7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h4.5a.5.5 0 0 0 0-1H1V8h4.5a.5.5 0 0 0 0-1H1zm9.5 0a.5.5 0 0 0 0 1H15v2h-4.5a.5.5 0 0 0 0 1H15a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1h-4.5z"/>
                </svg>
            </div>
            </div>

            <div class="flex justify-center">
            <div class="flex">
                <h1 class="text-gray-600 font-bold md:text-2xl text-xl upper">Update Task</h1>
            </div>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_task_name">Task Name</label>
                <input type="text" name="task_name" maxlength="100" required="" id="id_task_name" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Input 1" value="{{ task.task_name }}"/>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_last_date" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Last Date</label>
                <input type="text" name="last_date"  id="id_last_date" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Pick a Date"/>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_description" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_task_name">Description</label>
                <input type="text" name="description" maxlength="1000" id="id_description" class="py-8 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Input 1" value="{{ task.description }}"/>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_url" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Neccesary Url</label>
                <input type="url" name="url" maxlength="100" required="" id="id_url" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Input 3" value="{{ task.url }}"/>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_code" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Task Code</label>
                <input type="text" name="code" maxlength="8" id="id_code" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" type="text" placeholder="Input 3" value="{{ task.code }}"/>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7">
                <div class="grid grid-cols-1">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Status</label>
                    <select name="status" required="" id="id_status" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent" >
                        <option value="0">On Going</option>
                        <option value="1">Done</option>
                    </select>
                </div>

                <div class="grid grid-cols-1">
                    <label for="id_assign_status" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Assignment Status</label>
                    <select name="assign_status" required="" id="id_assign_status" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent">
                        <option value="0">Unassigned</option>

                        <option value="1">Assigned</option>

                    </select>
                </div>
            </div>

    
            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_member" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Update member</label>
                <select name="member" id="id_member" class="py-2 px-3 rounded-lg border-2 border-purple-700 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-800 focus:border-transparent">
                    
                    {% for user in users %}
                        <option value={{ user.id }}>{{ user.in_club_name }}</option>
                    {% endfor %}
                </select>
            </div>
            

            <div class='flex items-center justify-center  md:gap-8 gap-4 pt-5 pb-5'>
                <button class='w-auto bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'><a href="{% url "task_detail" task.pk %}">Cancel</a></button>
                <button type="submit" class='w-auto bg-purple-500 hover:bg-purple-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'>Update</button>
            </div>

        </div>
    </div>
</form>

{% endblock content %}