tasker/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from . import views

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('tasks', views.task_listings, name='task_listings'),
    path('calender', views.CalendarView.as_view(), name='calender_listings'),
    path('mytasks', views.own_task_listings, name='own_task_listings'),
    path('tasks_history', views.task_history, name='task_history'),
    path('rank', views.user_rank, name='user_rank'),
    path('announcements', views.announcements, name='announcements'),
    path('announcement_creation', views.announcement_creation,
         name='announcement_creation'),
    path('announcement/<int:pk>/', views.announcement, name='announcement'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('invite/', views.inviteView, name='invite'),
    path('create/', views.task_creation, name='task_creation'),
    path('member_list/', views.member_list, name='member_list'),
    path('task/<int:pk>/', views.task_detail, name='task_detail'),
    path('update/<int:pk>/', views.task_update, name='task_update'),
    path('delete/<int:pk>/', views.task_delete, name='task_delete'),
    path('task_done/<int:pk>/', views.task_done, name='task_done'),
    path('apply/<int:pk>/', views.task_apply, name='task_apply'),
    path('user/<int:pk>/', views.user_profile, name='user_profile'),
    path('edit/<int:pk>/', views.edit_profile, name='edit_profile'),
]

tasks/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


class Task(models.Model):

    assign_status_options = (
        (0, 'Unasigned'),
        (1, 'Assigned'),
    )

    status_options = (
        (0, 'On going'),
        (1, 'Done'),
    )

    task_name = models.CharField(max_length=100)
    assign_date = models.DateField(default=datetime.now, blank=True)
    last_date = models.DateField(default=datetime.now, blank=True)
    description = models.CharField(max_length=1000, blank=True)
    url = models.URLField(max_length=100, null=True)
    status = models.BooleanField(choices=status_options, null=True)
    assign_status = models.BooleanField(
        choices=assign_status_options, null=True, default=0)
    code = models.CharField(max_length=8, unique=True, null=True)
    member = models.ForeignKey(
        'User', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.task_name


class User(AbstractUser):

    designation_options = (
        ('General Member', 'General Member'),
        ('Executive', 'Executive'),
        ('Senior Executive', 'Senior Executive'),
        ('Assistant Director', 'Assistant Director'),
        ('Director', 'Director'),
    )

    department_options = (
        ('HR', 'Human Resources'),
    )

    status_options = (
        (0, 'Free'),
        (1, 'Busy'),
    )

    in_club_name = models.CharField(max_length=70, blank=True)
    department = models.CharField(
        max_length=50, choices=department_options, blank=True)
    designation = models.CharField(
        max_length=20, choices=designation_options, blank=True)
    display_picture = models.ImageField(blank=True, null=True)
    status = models.BooleanField(
        choices=status_options, default=1, null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    hr_points = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.in_club_name


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateField(default=datetime.now, blank=True)
    end_time = models.DateField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title


class Announcements(models.Model):

    tag = (
        (0, 'None'),
        (1, 'Everyone'),
    )

    title = models.CharField(max_length=200)
    picture = models.ImageField(blank=True, null=True)
    about = models.TextField(blank=True, null=True, max_length=1000)
    instructions = models.TextField(blank=True, null=True, max_length=1000)
    url = models.URLField(blank=True, null=True)
    tagged = models.BooleanField(choices=tag, default=0, null=True, blank=True)
    event_date = models.DateField(default=datetime.now, blank=True)
    duration = models.CharField(max_length=100, blank=True, null=True)
    platform = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.title

templates/user/edit_profile.html
{% extends 'base.html' %} {% block title %} | Edit {% endblock %} {% block content %} {% load static %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex h-screen bg-gray-200 items-center justify-center  mt-40 mb-40">
        <div class="grid bg-white rounded-lg shadow-xl w-11/12 md:w-9/12 lg:w-1/2">
            <div class="flex justify-center py-4">
                <div class="flex bg-purple-200 rounded-full md:p-4 p-2 border-2 border-purple-300">
                    <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
                </div>
            </div>

            <div class="flex justify-center">
                <div class="flex">
                    <h1 class="text-gray-600 font-bold md:text-2xl text-xl">Edit your Account</h1>
                </div>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_username">UserName</label>
                <input value="{{ request.user.username }}" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" id="id_username" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent"
                    type="text" placeholder="Input 1" />
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_in_club_name">In Club Name</label>
                <input value="{{ request.user.in_club_name }}" type="text" name="in_club_name" maxlength="70" id="id_in_club_name" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent"
                    type="text" placeholder="Input 1" />
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7">
                <div class="grid grid-cols-1">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_first_name">First Name</label>
                    <input value="{{ request.user.first_name }}" type="text" name="first_name" maxlength="150" id="id_first_name" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" type="text"
                        placeholder="Input 2" />
                </div>
                <div class="grid grid-cols-1">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_last_name">Last Name</label>
                    <input value="{{ request.user.last_name }}" type="text" name="last_name" maxlength="150" id="id_last_name" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" type="text"
                        placeholder="Input 3" />
                </div>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_email">Email</label>
                <input value="{{ request.user.email }}" type="email" name="email" maxlength="254" id="id_email" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" type="text" placeholder="Input 1"
                />
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7">
                <div class="grid grid-cols-1">
                    <label for="id_department" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Department</label>
                    <select name="department" id="id_department" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent">
                    <option value="HR">Human Resources</option>
                </select>
                </div>

                <div class="grid grid-cols-1">
                    <label for="id_designation" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold">Designation</label>
                    <select name="designation" id="id_designation" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent">
                    <option value="General Member">General Member</option>
                    <option value="Executive">Executive</option>
                    <option value="Senior Executive">Senior Executive</option>
                    <option value="Assistant Director">Assistant Director</option>
                    <option value="Director">Director</option>
                </select>
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-5 md:gap-8 mt-5 mx-7">
                <div class="grid grid-cols-1">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_password1">Password</label>
                    <input type="password" name="password1" autocomplete="new-password" id="id_password1" aria-autocomplete="list" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent"
                        type="text" placeholder="Input 2" />
                </div>
                <div class="grid grid-cols-1">
                    <label class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold" for="id_password2">Confim Password</label>
                    <input type="password" name="password2" autocomplete="new-password" id="id_password2" class="py-2 px-3 rounded-lg border-2 border-purple-300 mt-1 focus:outline-none focus:ring-2 focus:ring-purple-600 focus:border-transparent" type="text" placeholder="Input 3"
                    />
                </div>
            </div>

            <div class="grid grid-cols-1 mt-5 mx-7">
                <label for="id_display_picture" class="uppercase md:text-sm text-xs text-gray-500 text-light font-semibold mb-1">Upload Photo</label>
                <div class='flex items-center justify-center w-full'>
                    <label class='flex flex-col border-4 border-dashed w-full h-32 hover:bg-gray-100 hover:border-purple-300 group'>
                    <div class='flex flex-col items-center justify-center pt-7'>
                    <svg class="w-10 h-10 text-purple-400 group-hover:text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                    <p class='lowercase text-sm text-gray-400 group-hover:text-purple-600 pt-1 tracking-wider'>Select a photo</p>
                    </div>
                {% if user.display_picture %}
                    <input value="{{ request.user.display_picture.url }}" type="file" name="display_picture" accept="image/*" id="id_display_picture" lass="hidden" />
                {% else %}
                    <input type="file" name="display_picture" accept="image/*" id="id_display_picture" lass="hidden" />
                {% endif %}
                </label>
                </div>
            </div>

            <div class='flex items-center justify-center  md:gap-8 gap-4 pt-5 pb-5'>
                <button class='w-auto bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'><a href="{% url "task_listings" %}">Cancel</a></button>
                <button type="submit" class='w-auto bg-purple-500 hover:bg-purple-700 rounded-lg shadow-xl font-medium text-white px-4 py-2'>Create</button>
            </div>

        </div>
    </div>
</form>

{% endblock content %}

templates/user/user_profile.html
{% extends 'base.html' %}


{% block title %} / {{ user.in_club_name }} {% endblock %}


{% block content %}

{% load static %}

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    {% if request.user.id == user.id %}
        <h1 class="sm:text-3xl text-indigo-500 text-2xl font-medium title-font">Your Profile</h1>
    {% else %}
        <h1 class="sm:text-3xl text-indigo-500 text-2xl font-medium title-font">{{ user.first_name }}'s Profile</h1>
    {% endif %}
    
    <div class="flex mt-6 justify-center">
        <div class="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
    </div>
    
    {% if user.display_picture %}
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{{ user.display_picture.url }}">
    {% else %}
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
    {% endif %}
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">{{ user.first_name }} {{ user.last_name }}</h1>
      <p class="mb-8 leading-relaxed">In Club Name: {{ user.in_club_name }}</p>
      <p class="mb-8 leading-relaxed">HR points: {{ user.hr_points }}</p>

        {% if request.user.id == user.id %}
            <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a href="{% url 'edit_profile' user.id %}">Edit your profile</a></button>
        {% endif %}

      <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-3xl text-indigo-500 text-2xl font-medium title-font">{{ user.first_name }}'s Contributions</h1>
            <h2 class="sm:text-3xl text-gray-900 tracking-widest font-medium title-font mb-1">Successfully Completed {{ len_of_task }} tasks</h2>
            </div>
            <div class="flex flex-wrap -m-4">
            {% for task in tasks %}
                <div class="p-4 md:w-1/3">
                    <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                    <div class="flex items-center mb-3">
                        <div class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 text-white flex-shrink-0">

                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                        </div>
                        <h2 class="text-gray-900 text-lg title-font font-medium">{{ task.task_name }}</h2>
                    </div>
                    <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0"> 
                        <p class="leading-relaxed text-base">Assigned Date: {{ task.assign_date }}</p>
                        <p class="leading-relaxed text-base">Last Date: {{ task.last_date }}</p>
                    </div>
                    <div class="flex-grow">
                        <p class="leading-relaxed text-base"></p>
                        <a class="mt-3 text-indigo-500 inline-flex items-center" href="{% url 'task_detail' task.id %}">Learn More
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                            <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                        </a>
                    </div>
                    </div>
                </div>
            {% endfor %}

            </div>
        </div>
        </section>
    </div>
  </div>
</section>


{% endblock content %}